USE ULHT_DB26;
GO

-- A2. Explore the schema
SELECT *
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'HR';
GO

-- A3. Explore a relation
SELECT *
FROM HR.EMPLOYEES
WHERE LAST_NAME = 'SMITH';
GO

SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME
FROM HR.EMPLOYEES
WHERE LAST_NAME = 'Popp';
GO

-- A4. Filter rows
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE SALARY > 10000 AND DEPARTMENT_ID != 80
GO

-- A5. Work with missing values
SELECT FIRST_NAME, LAST_NAME
FROM HR.EMPLOYEES
WHERE MANAGER_ID IS NULL;
GO

-- A6. Related data
-- Find IT department number
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID, LOCATION_ID
FROM HR.DEPARTMENTS
WHERE DEPARTMENT_NAME = 'IT';
GO

-- List all employees in that department
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID = 60;
GO


-- Part B

-- B1. Check the identifier
SELECT *
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 651;
GO

-- B2. Verify nullable columns
SELECT COLUMN_NAME, IS_NULLABLE, DATA_TYPE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HR' AND TABLE_NAME = 'EMPLOYEES';
GO

-- B3. Insert a row
INSERT INTO HR.EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, DEPARTMENT_ID)
VALUES (651, 'Gonçalo', 'Almeida', '123.456.7890', GETDATE(), 'IT_PROG', 5000, 60);
GO

-- Part C

-- C1. Preview
SELECT *
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 651;
GO

-- C2. Delete
DELETE FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 651;
GO

-- C3. Verify
SELECT *
FROM HR.EMPLOYEES
WHERE EMPLOYEE_ID = 651;
GO