USE ULHT_DB26;
GO

SELECT * FROM sys.databases

SELECT * FROM INFORMATION_SCHEMA.SCHEMATA;

SELECT
    ORDINAL_POSITION,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'Scott'
  AND TABLE_NAME = 'EMP'
ORDER BY ORDINAL_POSITION;